### ISSUE TITLE
Place pending merges into a configurable backlog directory

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/dokuwiki-git-merge#6]
See the sample folder structure BitTorrent sync.
This directory should be configurable in the plugin settings.

**Comment by neutrinog** [comment]
One thought with making this configurable is we need to create githook that will build the backlog. 
If we do make the path configurable I don't know how we'll get that info to the githook.
Also, I would like to have all of the logic for generating the backlog to be contained within the plugin. e.g. a stand alone script that can be called by a githook to initiate the processing.

**Comment by neutrinog** [comment]
If there is a standard way to store files relating to a dokuwiki plugin perhaps we could just place the backlog in there and not make it configurable at all. Then we don't have to worry about getting that info to the script.

**Comment by kbuildsyourdotcom** [comment]
Looking into file placement and restructuring. Will update this issue in a few hours.

**Comment by kbuildsyourdotcom** [comment]
This is how things are handled in the latest commit of the plugin. The most recent action for each item is held in the JSON logs.
