### ISSUE TITLE
create a script that can be called by a githook that will process a repository

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/dokuwiki-git-merge#8]
We should be able to get a list of files that were changed since the last push.
We can use this info to update the backlog files appropriately.
Backlog files should be cleaned out automatically by the merge tool so this script may or may not need to create new files/directories.

Any existing files should be updated rather than replaced.

When changes have been made (which will be true for any/every push) the script will update the root change log file ([project]-[lang]-[chapter].json) as well as any chapter change log files.

**Comment by kbuildsyourdotcom** [comment]
This is handled in a similar and effective fashion in the latest commit.
